version: '3.8'

services:
  # Main development environment with GPU support
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - TZ=UTC
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/bash
    tty: true
    stdin_open: true

  # Jupyter notebook service
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # For scheduled pipeline execution later
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    command: python -m btc_usdt_pipeline.workflow.scheduler
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped