# Model hyperparameters and architecture configuration

random_forest:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1

xgboost:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1

lstm:
  units: 64
  epochs: 20
  batch_size: 32

# Add more model types and parameters as needed
